sudo: required
services:
  - docker

before_install: 
  - docker build -t manuelextra/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true manuelextra/docker-react npm run test -- --coverage